services:
  frontend:
    container_name: $SERVICE_NAME
    image: $IMAGE_NAME:$IMAGE_TAG
    command: bun run serve
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000

