version = 0.1
[default.deploy.parameters]
stack_name = "qwik-srvchecker-app"
resolve_s3 = true
s3_prefix = "qwik-srvchecker-app"
region = "eu-west-1"
profile = "jfedotov"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiUrl=\"\" ImageTag=\"\""
image_repositories = ["QwikBunServerSrvckecker=585768188093.dkr.ecr.eu-west-1.amazonaws.com/qwiksrvcheckerappafd9b9a1/qwikbunserversrvckeckere7ab203brepo"]


