org: ${env:SERVERLESS_ORG}
service: qwik-lambda-app
app: qwik-lambda-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  memorySize: 128
  timeout: 10
  stage: dev

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"
    environment:
        NODE_ENV: production
        API_URL: ${env:API_URL}


custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: true
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
